modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ikblibrary"
version = "${version}"
displayName = "ikbLib"
authors = "ikkyblob"
description = '''
Adds API for new density functions and fluid behaviour
'''
#logoFile = ""

[[dependencies.ikblibrary]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ikblibrary]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ikblibrary]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ikblibrary.mixins.json"
